In [20]:
#简化模型
import numpy as np
net = np.array([[0,0,0,1/3,0,0],
              [1/4,0,0,0,1/2,0],
              [0,1,0,1/3,1/2,0],
              [1/4,0,0,0,0,1],
              [1/4,0,1,1/3,0,0],
              [1/4,0,0,0,0,0]])
b = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
def simple(x,y):
    for i in range(100):
        y=np.dot(x,y)
    return y
result = simple(net,b)
print(result)

[1.47911420e-31 2.00000000e-01 4.00000000e-01 2.21867130e-31
 4.00000000e-01 7.39557098e-32]


In [21]:
#随机模型
def random(x,y,n):
    d=0.85
    for i in range(100):
        y=(1-d)/n+d*np.dot(x,y)
        print(y)
random(net,b,6)

[0.07222222 0.13125    0.28472222 0.20208333 0.24930556 0.06041667]
[0.08225694 0.14630208 0.29977431 0.09170139 0.33961806 0.04034722]
[0.05098206 0.18681727 0.3196765  0.07677474 0.32326982 0.0424796 ]
[0.04675284 0.17322336 0.3429372  0.07194135 0.32931156 0.03583369]
[0.04538338 0.17489239 0.33258065 0.06539361 0.34681498 0.03493498]
[0.04352819 0.18204034 0.33958309 0.0643387  0.33586571 0.03464397]
[0.0432293  0.17699267 0.34070651 0.06369711 0.34112467 0.03424974]
[0.04304752 0.17916421 0.33846927 0.06329851 0.34183428 0.03418623]
[0.04293458 0.17942716 0.34050372 0.06320589 0.33978105 0.0341476 ]
[0.04290834 0.17853054 0.33982837 0.06314906 0.3414601  0.0341236 ]
[0.04289223 0.17923856 0.33976374 0.06312308 0.34086437 0.03411802]
[0.04288487 0.17898196 0.34010501 0.06311492 0.34079865 0.0341146 ]
[0.04288256 0.17895246 0.33985665 0.06311044 0.34108485 0.03411304]
[0.04288129 0.17907361 0.33995195 0.06310862 0.34087199 0.03411254]
[0.04288078 0.17898287 0.33996394 0.06310794 0.3